# Generated by Django 4.2 on 2024-11-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='type',
            field=models.CharField(choices=[('kirim', 'kirim'), ('chiqim', 'chiqim')], default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('tasdiqlangan', 'tasdiqlangan'), ('tasdiqlanmagan', 'tasdiqlanmagan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
