# Generated by Django 4.2 on 2024-11-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemproduct',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
