# Generated by Django 4.2 on 2024-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_orderproduct_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='image',
            field=models.ImageField(upload_to='product/category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/product/'),
        ),
    ]
