# Generated by Django 4.2 on 2024-11-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_cartitemproduct_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
