# Generated by Django 4.2 on 2024-11-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.CharField(choices=[('band', 'band'), ('band emas', 'band emas')], default='band emas', max_length=20),
        ),
    ]
