# Generated by Django 4.2 on 2024-11-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfood',
            options={'verbose_name': 'kategoriya taom', 'verbose_name_plural': 'kategoriylar taom'},
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_composition',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_composition_en',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_composition_ru',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_composition_uz',
        ),
        migrations.RemoveField(
            model_name='food',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='food',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='food',
            name='name_uz',
        ),
    ]
