# Generated by Django 4.2 on 2024-11-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
