# Generated by Django 4.2 on 2024-11-06 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_alter_table_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='in_contact',
            new_name='is_confirm',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('jarayonda', 'jarayonda'), ('bajarildi', 'bajarildi')], default='jarayonda', max_length=20),
        ),
    ]
