# Generated by Django 5.1.3 on 2024-11-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_categoryfood_name_alter_categoryfood_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('kirim', 'kirim'), ('chiqim', 'chiqim')], default='kirim', max_length=20),
        ),
    ]
