# Generated by Django 4.2 on 2024-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfood',
            name='image',
            field=models.ImageField(upload_to='common/category/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='common/food/'),
        ),
    ]
