# Generated by Django 4.2 on 2024-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_categoryfood_image_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
