# Generated by Django 4.2 on 2024-12-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_food_name_en_food_name_ru_food_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.table'),
        ),
    ]
