# Generated by Django 4.2 on 2024-11-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('afitsant', 'afitsant'), ('kassir', 'kassir'), ('omborchi', 'omborchi'), ('oshpaz', 'oshpaz')], max_length=50),
        ),
    ]
