# Generated by Django 4.2 on 2024-11-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
