# Generated by Django 4.2 on 2024-11-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('hodimlar oyligi', 'hodimlar oyligi'), ('komunal tolovlar', 'komunal tolovlar'), ('reklama marketing', 'reklama marketing'), ('ijara tolov', 'ijara tolov')], max_length=250),
        ),
    ]
