# Generated by Django 5.1.3 on 2024-11-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_payment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('kirim', 'kirim'), ('chiqim', 'chiqim')], default='chiqim', max_length=120),
        ),
    ]
