# Generated by Django 5.1.3 on 2024-11-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
